name = "create-final"
author = "none"
version = "4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2dcd44604b7888094ba648708217a0159fe8b2ceff34dc82ce927590fa83cdb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
