name = "create-final"
author = "none"
version = "4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e146bce5f37e2da82fffc4d0f5cf90c81540fdf9e99a0d6af6ddc67b518d3a7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
